# Generated by Django 2.2.6 on 2020-01-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='res_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
