# Generated by Django 2.2.6 on 2020-01-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200103_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
